FROM debian:latest

RUN apt-get -qq update && apt-get -y install g++

## docker build -t buffertly/cppcompiler .
## docker push -q buffertly/cppcompiler
# docker run -dit --name cppcompiler -v $PWD:/opt buffertly/cppcompiler

